# Generated by Django 4.1.5 on 2023-06-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(default=None)),
                ('roles', models.ManyToManyField(related_name='staffs', to='api.role')),
            ],
        ),
    ]
