# Generated by Django 4.1.5 on 2023-06-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_star', models.FloatField(default=0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.movie')),
            ],
        ),
    ]
